# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x19\n\x0bNameRequest\x12\n\n\x02id\x18\x01 \x02(\t\"\x95\x01\n\tNameReply\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06nconst\x18\x02 \x02(\t\x12\x13\n\x0bprimaryName\x18\x03 \x02(\t\x12\x11\n\tbirthYear\x18\x04 \x02(\t\x12\x11\n\tdeathYear\x18\x05 \x02(\t\x12\x19\n\x11primaryProfession\x18\x06 \x02(\t\x12\x16\n\x0eknownForTitles\x18\x07 \x02(\t2-\n\x04Name\x12%\n\x07getName\x12\x0c.NameRequest\x1a\n.NameReply\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NAMEREQUEST']._serialized_start=17
  _globals['_NAMEREQUEST']._serialized_end=42
  _globals['_NAMEREPLY']._serialized_start=45
  _globals['_NAMEREPLY']._serialized_end=194
  _globals['_NAME']._serialized_start=196
  _globals['_NAME']._serialized_end=241
# @@protoc_insertion_point(module_scope)
