# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class NameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getName = channel.unary_unary(
                '/Name/getName',
                request_serializer=service__pb2.NameRequest.SerializeToString,
                response_deserializer=service__pb2.NameReply.FromString,
                )


class NameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getName(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getName': grpc.unary_unary_rpc_method_handler(
                    servicer.getName,
                    request_deserializer=service__pb2.NameRequest.FromString,
                    response_serializer=service__pb2.NameReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Name', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Name(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Name/getName',
            service__pb2.NameRequest.SerializeToString,
            service__pb2.NameReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
